#' Convert raw JSON format file to an R-friendly tibble
#'
#' \code{json_to_tibble} creates an R-friendly tibble() object from the raw JSON
#' data extracted by \code{query_fulcrum}. It discards the metadata included
#' in the JSON payload which is probably not useful information for our
#' analysis. Use the output dataframes for subsequent analysis and checking.
#' Don't overwrite the objects you create with this function during data
#' wrangling as they should be used as the base dfs to run all checks and build
#' the final data outputs in RShiny.
#'
#' @param json_obj A JSON formatted object, generated by \code{query_fulcrum}
#' @return The datatable section of the JSON file as a tibble.
#' @export

json_to_tibble <- function(json_obj){
  x <- httr::content(json_obj, as = "text") %>%
    jsonlite::fromJSON(.) %>% # Converts from JSON to R object
    magrittr::extract(2) %>% # extract(2) returns rows from the data (as opposed to the columns if using extract(1))
    dplyr::as_tibble(.)
}
