#' A better version of \code{json_to_tibble} to convert raw JSON format file to an R-friendly tibble
#'
#' \code{json_to_tibble2} creates an R-friendly tibble() object from the raw JSON
#' data extracted by \code{query_fulcrum}. It discards the metadata included
#' in the JSON payload which is probably not useful information for our
#' analysis. Use the output dataframes for subsequent analysis and checking.
#' Don't overwrite the objects you create with this function during data
#' wrangling as they should be used as the base dfs to run all checks and build
#' the final data outputs in RShiny.
#'
#' @param json_obj A JSON formatted object, generated by \code{query_fulcrum}
#'
#' @return The datatable section of the JSON file as a tibble.
json_to_tibble2 <- function(json_obj){
  x <- httr::content(json_obj, as = "text") %>%
    jsonlite::fromJSON(.) # Converts from JSON to R object

  if (length(x$rows) == 0){
    x <- x$fields$name %>% # create logical tibble with named columns but zero rows
      purrr::map_dfc(stats::setNames, object = list(character()))
  } else {
    x <- x %>%
      magrittr::extract2(2) %>% # extract(2) returns data in rows from the data
      dplyr::as_tibble(.)
  }
  return(x)
}
